--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "KYJ"."SEQ_BOARD_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 19 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMM_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "KYJ"."SEQ_COMM_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "KYJ"."BOARD" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"OFILE" VARCHAR2(200 BYTE), 
	"SFILE" VARCHAR2(30 BYTE), 
	"VISITCOUNT" NUMBER DEFAULT 0, 
	"LIKEBOARD" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMM
--------------------------------------------------------

  CREATE TABLE "KYJ"."COMM" 
   (	"IDX" NUMBER, 
	"BOARDIDX" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"COMM" VARCHAR2(2000 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "KYJ"."MEMBER" 
   (	"ID" VARCHAR2(10 BYTE), 
	"PASS" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"TEL" VARCHAR2(15 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QNABOARD
--------------------------------------------------------

  CREATE TABLE "KYJ"."QNABOARD" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"OFILE" VARCHAR2(200 BYTE), 
	"SFILE" VARCHAR2(30 BYTE), 
	"VISITCOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KYJ.BOARD
SET DEFINE OFF;
Insert into KYJ.BOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,VISITCOUNT,LIKEBOARD) values (11,'전장군','111','111',to_date('24/07/19','RR/MM/DD'),'unnamed.png','20240719_125657399.png',45,29);
Insert into KYJ.BOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,VISITCOUNT,LIKEBOARD) values (10,'전장군','12345','12345',to_date('24/07/19','RR/MM/DD'),null,null,44,0);
Insert into KYJ.BOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,VISITCOUNT,LIKEBOARD) values (1,'김유신','제목1 입니다.','내용1',to_date('24/07/15','RR/MM/DD'),null,null,1,0);
Insert into KYJ.BOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,VISITCOUNT,LIKEBOARD) values (2,'이장군','제목2 입니다.','내용2',to_date('24/07/15','RR/MM/DD'),null,null,0,0);
Insert into KYJ.BOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,VISITCOUNT,LIKEBOARD) values (3,'박병사','제목3 입니다.','내용3',to_date('24/07/15','RR/MM/DD'),null,null,1,0);
Insert into KYJ.BOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,VISITCOUNT,LIKEBOARD) values (4,'전하사','제목4 입니다.','내용4',to_date('24/07/15','RR/MM/DD'),null,null,17,0);
REM INSERTING into KYJ.COMM
SET DEFINE OFF;
Insert into KYJ.COMM (IDX,BOARDIDX,NAME,COMM,POSTDATE) values (11,14,'전장군','ㅎㅇ',to_date('24/07/19','RR/MM/DD'));
Insert into KYJ.COMM (IDX,BOARDIDX,NAME,COMM,POSTDATE) values (15,14,'전장군','ㅎㅇ',to_date('24/07/19','RR/MM/DD'));
Insert into KYJ.COMM (IDX,BOARDIDX,NAME,COMM,POSTDATE) values (12,14,'전장군','하위',to_date('24/07/19','RR/MM/DD'));
REM INSERTING into KYJ.MEMBER
SET DEFINE OFF;
Insert into KYJ.MEMBER (ID,PASS,NAME,EMAIL,TEL,REGIDATE) values ('addid3','1234','전장하','addid3@naver.com','01020554894',to_date('24/07/19','RR/MM/DD'));
Insert into KYJ.MEMBER (ID,PASS,NAME,EMAIL,TEL,REGIDATE) values ('addid1','1234','전장군','addid1@naver.com','01012345555',to_date('24/07/16','RR/MM/DD'));
Insert into KYJ.MEMBER (ID,PASS,NAME,EMAIL,TEL,REGIDATE) values ('dsfdsf','1234','re','re','re',to_date('24/07/23','RR/MM/DD'));
Insert into KYJ.MEMBER (ID,PASS,NAME,EMAIL,TEL,REGIDATE) values ('1231231','1234','er','re','re',to_date('24/07/23','RR/MM/DD'));
Insert into KYJ.MEMBER (ID,PASS,NAME,EMAIL,TEL,REGIDATE) values ('test123','1234','df','df','010-1234-5678',to_date('24/07/23','RR/MM/DD'));
Insert into KYJ.MEMBER (ID,PASS,NAME,EMAIL,TEL,REGIDATE) values ('addid2','1234','김하사','addid2@naver.com','01012345678',to_date('24/07/18','RR/MM/DD'));
REM INSERTING into KYJ.QNABOARD
SET DEFINE OFF;
Insert into KYJ.QNABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,VISITCOUNT) values (15,'전장군','커뮤3','커뮤3',to_date('24/07/19','RR/MM/DD'),'video.mp4','20240719_152519934.mp4',24);
Insert into KYJ.QNABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,VISITCOUNT) values (13,'전장군','커뮤니티1','커뮤니티1',to_date('24/07/19','RR/MM/DD'),null,null,2);
Insert into KYJ.QNABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,VISITCOUNT) values (14,'전장군','커뮤니티2수정','커뮤니티2수정',to_date('24/07/19','RR/MM/DD'),null,null,58);
Insert into KYJ.QNABOARD (IDX,NAME,TITLE,CONTENT,POSTDATE,OFILE,SFILE,VISITCOUNT) values (18,'df','123','123',to_date('24/07/23','RR/MM/DD'),'like.png','20240723_164838275.png',1);
--------------------------------------------------------
--  DDL for Index SYS_C008416
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYJ"."SYS_C008416" ON "KYJ"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008422
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYJ"."SYS_C008422" ON "KYJ"."BOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008433
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYJ"."SYS_C008433" ON "KYJ"."QNABOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008438
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYJ"."SYS_C008438" ON "KYJ"."COMM" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008422
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYJ"."SYS_C008422" ON "KYJ"."BOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008438
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYJ"."SYS_C008438" ON "KYJ"."COMM" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008416
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYJ"."SYS_C008416" ON "KYJ"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008433
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYJ"."SYS_C008433" ON "KYJ"."QNABOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "KYJ"."BOARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."BOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."BOARD" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."BOARD" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KYJ"."BOARD" MODIFY ("LIKEBOARD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMM
--------------------------------------------------------

  ALTER TABLE "KYJ"."COMM" MODIFY ("BOARDIDX" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."COMM" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."COMM" MODIFY ("COMM" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."COMM" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."COMM" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "KYJ"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."MEMBER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."MEMBER" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."MEMBER" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QNABOARD
--------------------------------------------------------

  ALTER TABLE "KYJ"."QNABOARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."QNABOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."QNABOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."QNABOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."QNABOARD" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
  ALTER TABLE "KYJ"."QNABOARD" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
